version: '3'
services:
  web:
    environment:
      - NODE_ENV=development
      - API_PUBLIC_HOSTNAME=http://localhost
      - API_INTERNAL_HOSTNAME=http://api:5001
    volumes:
      - "/c/Projects/oleksiionsoftware.com:/app"
    ports:
      - "9229:9229"