version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./OleksiiOnSoftware.Config.Nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
  redis:
    container_name: redis
    image: "redis:alpine"
  command_handler:
    container_name: command_handler
    build:
      context: .
      dockerfile: ./OleksiiOnSoftware.Services.Blog.CommandHandler/Dockerfile
  event_handler:
    container_name: event_handler
    build:
      context: .
      dockerfile: ./OleksiiOnSoftware.Services.Blog.EventHandler/Dockerfile
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./OleksiiOnSoftware.Services.Blog.Api/Dockerfile
    ports:
      - "5001:5001"
  web:
    container_name: web
    build: 
      context: .
      dockerfile: ./OleksiiOnSoftware.Apps.Blog/Dockerfile
    environment: 
      - NODE_ENV=production
      - NODE_PORT=3000
      - NODE_HOSTNAME=0.0.0.0
    ports:
      - "3000:3000"
  startup:
    container_name: startup
    build:
      context: .
      dockerfile: ./OleksiiOnSoftware.Services.Blog.Import/Dockerfile
