// flow-typed signature: e9fd48abe1d506227796528f33102d42
// flow-typed version: <<STUB>>/url-search-params-polyfill_v^1.2.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-search-params-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-search-params-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'url-search-params-polyfill/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'url-search-params-polyfill/index' {
  declare module.exports: $Exports<'url-search-params-polyfill'>;
}
declare module 'url-search-params-polyfill/index.js' {
  declare module.exports: $Exports<'url-search-params-polyfill'>;
}
declare module 'url-search-params-polyfill/test/index.test.js' {
  declare module.exports: $Exports<'url-search-params-polyfill/test/index.test'>;
}
